[project]
name = "the-daily-collage"
version = "0.1.0"
description = "Handles anything to do with data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.124.2",
]
